

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: myapp_api
    ports:
      - "3000:3000"

  nginx:
    image: nginx:stable
    container_name: myapp_nginx
    ports:
      - "80:80"
    volumes:
      # Serve frontend files
      - ./frontend:/usr/share/nginx/html:ro
      # Custom nginx config
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api

